"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle Tn = n(n + 1) / 2 1,3,6,10,15,...     
Pentagonal Pn = n(3n - 1) / 2 1,5,12,22,35
Hexagonal Hn = n(2n - 1) 1,6,15,28,45       
    
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
import math

def is_pentagonal(num):
    n = (1 + math.sqrt(1 + 24 * num)) / 6
    return n.is_integer()

def next_triangle():
    n = 144  # Start with the first hexagonal number after the known value
    while True:
        hexagonal = n * (2 * n - 1)
        if is_pentagonal(hexagonal):
            return hexagonal
        n += 1

result = next_triangle()
print(result)